### ISSUE TITLE
Add support for Kubo MFS 

### ISSUE THREAD

**Issue by Arlodotexe** [ipfs-shipyard/net-ipfs-core#11]
# The problem
The Core API does not have a way to interact with MFS.

# The solution
Create a new interface and the types needed for interacting with MFS via the Core API. This includes all endpoints under `/api/v0/files/`.

Reference:
- https://docs.ipfs.tech/concepts/file-systems/#mutable-file-system-mfs
- https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-files-ls

**Comment by Derrick-** [comment]
I have this written, I'll PR soon

See also
https://github.com/ipfs-shipyard/net-ipfs-http-client/issues/14
