### ISSUE TITLE
Let's go for a multi-project layout rather than splitting code

### ISSUE THREAD

**Issue by stevefan1999-personal** [ipfs-shipyard/net-ipfs-core#16]
Here's what I think we should do:

1. Merge https://github.com/richardschneider/peer-talk
2. Merge https://github.com/ipfs-shipyard/net-ipfs-http-client as well
3. Rename this into ipfs-net (maybe)

**Comment by Derrick-** [comment]
Ipfs Engine, which is currently not being maintained also relies on Ipfs-Core. Is there anything else derived from Core that we should be aware of?
How would this impact NuGet builds/integration/updates?

**Comment by Derrick-** [comment]
I see what you've done now. I like it.
If there's a good time to do this, it's probably now.

**Comment by stevefan1999-personal** [comment]
@Derrick- I also used a git merge tool so that all of the code from Richard is cleanly imported back in. In addition I have used one of the fork [Myina/peer-talk: Peer to peer communication from Richard Schneider (github.com)](https://github.com/Myina/peer-talk) for the PeerTalk library since it is the only fork that has recent history. 

@Myina do you agree so we could use your fork in the merger?

**Comment by Myina** [comment]
Yes. I do agree.

**Comment by erikma** [comment]
@stevefan1999-personal one ask on your new layout (if others agree), please avoid using the full namespace in directory names, as it makes console navigation harder (much more typing before getting good `tab` based autocomplete). IOW rename 'IpfsShipyard.Ipfs.Core' to just 'Core', 'IpfsShipyard.Ipfs.Core.Tests' to 'Core.Tests', and so on.

**Comment by stevefan1999-personal** [comment]
@erikmav So should I set `RootNamespace` instead?

**Comment by stevefan1999-personal** [comment]
@erikmav So should I set `RootNamespace` instead?

**Comment by erikmav** [comment]
The directory names don't factor into default namespaces: RootNamespace will default to the base filename of the csproj. If you rename the csproj files to a shorter name then you need RootNamespace.

**Comment by erikmav** [comment]
See comment I made on your commit. Thanks for adding in fix for #20

**Comment by erikmav** [comment]
@Derrick- when this goes in you should add an issue to Richard's PeerTalk issues list to point to the aggregated repo, as was done for the other original repos.

**Comment by Arlodotexe** [comment]
From https://github.com/ipfs-shipyard/net-ipfs-http-client/issues/23#issuecomment-1512007459

> 
> When we migrated from Richard's repositories, we kept these separate because other people may still implement the Core API without knowing or caring about the HTTP client.
> 
> `net-ipfs-http-client` is currently the only library (that I know of) which implements the `net-ipfs-core`. This is "fine", our only good and up-to-date option is to bootstrap Kubo, which works with the HTTP API.
> 
> But in the future, I expect to see these implementations for `net-ipfs-core`:
> - .NET bindings for `gomobile-ipfs` that works on Xamarin / Uno Platform
> - .NET bindings for `js-ipfs` that works with Uno Platform WASM
> - .NET bindings for `ipfs-wasm`, whenever that project is ready.
> - Anything created by the IPFS community. Could create a `libp2p-sharp` and try from scratch, or try reviving Richard's `net-ipfs-engine`.
> 
> I need those first 2 for my own projects, but seeing `ipfs-wasm` come to .NET would be a near-perfect option. Full managed access to IPFS and libp2p, no bootstrapping or API overhead. The same code running everywhere, and someone to maintain it.
> 
> So while combining the repos seems like a good idea now, it would make it harder to grow the IPFS ecosystem for .NET in the long run. The need for dual-PRs will slow as we get things tidied up and brought into 2023
