### ISSUE TITLE
Set up .editorconfig and clean up code

### ISSUE THREAD

**Issue by Arlodotexe** [ipfs-shipyard/net-ipfs-core#9]
# The problem
The project does not have an EditorConfig. There is no IDE guidance in terms of code style.

# The solution
To keep things clean for all developers on this project, we need to set up the .editorconfig file so Visual Studio and Rider automatically follow the correct coding conventions.

**Comment by erikmav** [comment]
@Arlodotexe do you have a specific .editorconfig in mind for styling?

**Comment by Arlodotexe** [comment]
I haven't taken the time to set one up - I left most of Richard's code as is. It's up to us to decide what we want for the editorconfig.  Will come back to this later.
